### ISSUE TITLE
[BUG] Alias avec MyCommand

### ISSUE THREAD

**Issue by Bricec6** [Triozer/spigot-mention-player#2]
Bonjour il y a  un bug avec l'alias MyCommand

https://i.imgur.com/BeP5fsh.png

en jeu:
https://pastebin.com/5sZcXanQ

Comment c'est arrivé?
Je voulais que quand mon joueur clique sur un item dans mon menu deluxemenu sa vas directement au /mention GUI. 

merci.

**Comment by triozer** [comment]
Hello 👋 , ton message a bien été pris en compte. Je vais regarder ça en détail quand j'aurai du temps.

> Hello 👋 , your message has been taken into account. I'll look into it in detail when I have time.

**Comment by triozer** [comment]
Alors, ce n'est pas un bug de mon côté, de ce que je vois c'est plus la manière dont `MyCommand` fonctionne.

**Comment by Bricec6** [comment]
C'était de ma faute désolé.
