### ISSUE TITLE
Traduction

### ISSUE THREAD

**Issue by Bricec6** [Triozer/spigot-mention-player#4]
Bonjour, votre plugin a un potentiel énorme!
J'en est jamais vu un aussi complet sauf que... presque rien n'est traduisable... On a des BLOCK_NOTE_BELL etc.. c'est très laid sans mentir.

Il faudrait pouvoir le modifier entièrement pour le mettre en place sur nos serveurs, sans ca il ne verra pas le jour sur de gros serveur et c'est bien dommage ;)

cordialement

**Comment by triozer** [comment]
Content de pouvoir te montrer #7. Une mise à jour du plugin est en cours.
